language: python
sudo: false

python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
  - "3.10"
  - "pypy"  # PyPy2 2.5.0
  - "pypy3"
  - "pypy-5.3.1"

install:
    python setup.py install

script: python -m unittest odict.tests
